import React from 'react';
import ReactDOM from 'react-dom/client';
import { AppProvider } from './context/AppContext';
import App from './App';
import './index.css';

// Register the Workbox service worker generated by vite-plugin-pwa.
// `autoUpdate` mode (set in vite.config.ts) means: when a new SW is
// available, it activates immediately on the next page navigation
// without prompting the user — ideal for training centres where
// users shouldn't have to manage updates manually.
import { registerSW } from 'virtual:pwa-register';

let refreshing = false;
if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!refreshing) {
      refreshing = true;
      window.location.reload();
    }
  });
}

const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    console.log('[VikasSetu] New version detected, updating Service Worker...');
    updateSW(true);
  },
  onOfflineReady() {
    console.log('[VikasSetu] App is ready to work offline.');
  },
  onRegistered(r) {
    if (r) {
      // Check for SW updates on every registration and every 5 minutes
      r.update();
      setInterval(
        () => {
          r.update();
        },
        5 * 60 * 1000,
      );
    }
  },
  onRegisterError(error) {
    console.error('[VikasSetu] Service worker registration error:', error);
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AppProvider>
      <App />
    </AppProvider>
  </React.StrictMode>,
);
